# Generated by Django 3.2.7 on 2021-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gelombang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelombang', models.IntegerField(verbose_name='Gelombang')),
                ('linkOpenLearning', models.CharField(blank=True, max_length=50)),
                ('linkAksesKelas', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Data Peserta',
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nidn', models.CharField(max_length=10)),
                ('institusi_asal', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gelombang', models.IntegerField()),
                ('nomer_telp', models.CharField(max_length=50, verbose_name='NOMER TELEPON')),
                ('link_transfer', models.CharField(max_length=50)),
                ('link_penugasan', models.CharField(max_length=50)),
                ('link_kesanggupan', models.CharField(max_length=50)),
                ('is_validated', models.BooleanField(verbose_name='Status Validasi')),
                ('linkSertifikat', models.CharField(blank=True, max_length=50, verbose_name='Sertifikat')),
            ],
            options={
                'verbose_name_plural': 'Data Peserta',
            },
        ),
    ]
