# Generated by Django 3.2.7 on 2021-10-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pekerti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gelombang',
            options={'verbose_name_plural': 'Data Pelaksanaan Gelombang'},
        ),
        migrations.RemoveField(
            model_name='gelombang',
            name='id',
        ),
        migrations.AlterField(
            model_name='gelombang',
            name='gelombang',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Gelombang'),
        ),
        migrations.AlterField(
            model_name='gelombang',
            name='linkAksesKelas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Class Access Code'),
        ),
        migrations.AlterField(
            model_name='gelombang',
            name='linkOpenLearning',
            field=models.CharField(blank=True, max_length=50, verbose_name='OpenLearning Link'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='gelombang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pekerti.gelombang', verbose_name='Gelombang'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='institusi_asal',
            field=models.CharField(max_length=50, verbose_name='Institusi Asal'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_kesanggupan',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_penugasan',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_transfer',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama',
            field=models.CharField(max_length=50, verbose_name='Nama Peserta'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nidn',
            field=models.CharField(max_length=10, verbose_name='NIDN'),
        ),
    ]
