# Generated by Django 3.2.7 on 2021-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekerti', '0002_auto_20211008_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelombang',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Berakhir'),
        ),
        migrations.AddField(
            model_name='gelombang',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Mulai'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_kesanggupan',
            field=models.CharField(max_length=50, verbose_name='Dokumen Kesanggupan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_penugasan',
            field=models.CharField(max_length=50, verbose_name='Dokumen Penugasan'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='link_transfer',
            field=models.CharField(max_length=50, verbose_name='Bukti Transfer'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nomer_telp',
            field=models.CharField(max_length=50, verbose_name='Nomer Telepon'),
        ),
    ]
