# Generated by Django 3.2.8 on 2021-10-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pekerti', '0004_auto_20211008_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gelombang',
            old_name='linkAksesKelas',
            new_name='link_akses_kelas',
        ),
        migrations.RenameField(
            model_name='gelombang',
            old_name='linkOpenLearning',
            new_name='link_openlearning',
        ),
        migrations.RenameField(
            model_name='peserta',
            old_name='linkSertifikat',
            new_name='link_sertifikat',
        ),
    ]
