# Generated by Django 3.2.8 on 2021-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekerti', '0005_auto_20211008_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='id',
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nidn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='NIDN'),
        ),
    ]
